---
- hosts: web
  become: yes
  tasks:
    - name: Stop existing container
      docker_container:
        name: myapp
        state: absent

    - name: Run new container
      docker_container:
        name: myapp
        image: abhi2404/devops-project5
        state: started
        ports:
          - "80:80"
